"use client";
import type { Metadata } from "next";
import "jsvectormap/dist/jsvectormap.css";
import "./globals.css";
import React, { useEffect, useState } from "react";
import Loader from "@/components/common/Loader";
import Providers from "@/lib/Providers";
import { Toaster } from "react-hot-toast";

const metadata: Metadata = {
  title: "Aves digital Admin",
  description: "Generated by Tasimul Alam",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <Providers>
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
          <Toaster position="top-right"/>
          {loading ? <Loader /> : children}
        </div>
      </body>
    </html>
    </Providers>
  );
}
