
import { Metadata } from "next";
import React from 'react';
import DefaultLayout from "@/components/Layouts/DefaultLayout";
import MainDashboard from "@/components/Dashboard/MainDashboard";

export const metadata: Metadata = {
  title: "Aves Digital Admin",
  description: "Generated by TripNest Limited",
};

export default function Home() {
  return (
    <>
      <DefaultLayout>
        <MainDashboard />
      </DefaultLayout>
   </>
  );
}
